# Generated by Django 5.1.6 on 2025-12-29 14:54

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_fr', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('name_es', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Blog category',
                'verbose_name_plural': 'Blog categories',
            },
            bases=(core.models.LocalizedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_fr', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('name_es', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Blog tag',
                'verbose_name_plural': 'Blog tags',
            },
            bases=(core.models.LocalizedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('language', models.CharField(default='fr', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog subscriber',
                'verbose_name_plural': 'Blog subscribers',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('title_fr', models.CharField(max_length=250)),
                ('title_en', models.CharField(blank=True, max_length=250)),
                ('title_es', models.CharField(blank=True, max_length=250)),
                ('excerpt_fr', models.TextField(blank=True)),
                ('excerpt_en', models.TextField(blank=True)),
                ('excerpt_es', models.TextField(blank=True)),
                ('content_fr', models.TextField()),
                ('content_en', models.TextField(blank=True)),
                ('content_es', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('newsletter_sent', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='core.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='core.blogtag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
            bases=(core.models.LocalizedFieldMixin, models.Model),
        ),
    ]
