# Generated by Django 5.1.4 on 2025-12-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_es',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt_es',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='blogtag',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='blogtag',
            name='name_es',
        ),
    ]
