"""Site pages for Dr Bronstein."""

from django.http import Http404
from django.shortcuts import render


EXAMS = [
	{
		"slug": "gastroscopie",
		"title": "Gastroscopie",
		"image": "/static/img/exams/gastroscopie.jpg",
		"description": "Explorations oeso-gastriques et duodénales.",
		"indications": ["Brûlures, reflux, douleurs hautes", "Anémie, vomissements, suspicion d'ulcère"],
		"preparation": "Jeûne de 6h pour les solides et 2h pour les liquides clairs, selon consignes de l'anesthésie.",
		"procedure": "Examen endoscopique sous anesthésie ou sédation courte, durée environ 10 minutes.",
		"aftercare": "Repos court, reprise alimentaire légère après avis médical; ne pas conduire en cas de sédation.",
		"duration": "Environ 10 minutes (hors préparation et réveil).",
		"risks": [
			"Sédation : somnolence transitoire (ne pas conduire le jour même)",
			"Très rares complications : saignement, perforation (expliquées avant l'examen)",
		],
		"documents": [
			{"label": "Consignes fibroscopie (en ligne)", "url": "/guides/#deroulement-fibroscopie"},
		],
	},
	{
		"slug": "coloscopie",
		"title": "Coloscopie",
		"image": "/static/img/exams/coloscopie.jpg",
		"description": "Prévention et diagnostic des maladies du côlon.",
		"indications": ["Dépistage colorectal", "Sang dans les selles, diarrhée chronique, douleurs abdominales"],
		"preparation": "Régime pauvre en résidus et laxatif la veille selon l'ordonnance.",
		"procedure": "Examen endoscopique sous anesthésie courte; polypes retirés si besoin.",
		"aftercare": "Surveillance courte, ballonnements possibles; signes d'alerte expliqués avant la sortie.",
		"duration": "Environ 20 à 30 minutes (hors préparation et réveil).",
		"risks": [
			"Ballonnements transitoires après l'examen",
			"Risque faible de saignement ou perforation (notamment si polype retiré)",
		],
		"documents": [
			{"label": "Préparation coloscopie (en ligne)", "url": "/guides/#preparation-coloscopie"},
		],
	},
	{
		"slug": "echographie",
		"title": "Échographie",
		"image": "/static/img/exams/echographie.jpg",
		"description": "Échographie abdominale et pelvienne.",
		"indications": ["Bilan hépatique", "Douleurs abdominales", "Surveillance biliaire ou pancréatique"],
		"preparation": "À jeun selon l'organe exploré; consignes précisées lors du rendez-vous.",
		"procedure": "Examen indolore avec sonde sur l'abdomen, gel posé sur la peau.",
		"aftercare": "Reprise immédiate des activités; compte-rendu oral puis écrit.",
		"duration": "Environ 10 à 20 minutes selon l'organe exploré.",
		"risks": ["Aucun risque connu, examen non irradiant."],
		"documents": [],
	},
	{
		"slug": "hepatologie",
		"title": "Hépatologie",
		"image": "/static/img/exams/hepatologie.jpg",
		"description": "Suivi des maladies du foie et bilan hépatique.",
		"indications": ["Bilan enzymes hépatiques", "Foie gras non alcoolique", "Surveillance hépatite"],
		"preparation": "Bilan sanguin préalable selon prescription.",
		"procedure": "Consultation spécialisée, éventuel complément échographique ou fibroscan.",
		"aftercare": "Plan de suivi personnalisé (biologie, imagerie, hygiène de vie).",
		"duration": "Consultation de 20 minutes environ; examens complémentaires selon indication.",
		"risks": ["Aucun risque spécifique en consultation; risques propres aux examens complémentaires expliqués le cas échéant."],
		"documents": [],
	},
	{
		"slug": "echo-endoscopie",
		"title": "Echo-endoscopie",
		"image": "/static/img/exams/echo-endoscopie.jpg",
		"description": "Explorations écho-endoscopiques haute et basse.",
		"indications": ["Exploration biliaire/pancréatique", "Kystes, masses digestives"],
		"preparation": "Jeûne et préparation digestive selon indication.",
		"procedure": "Endoscope équipé d'une sonde d'échographie pour visualiser les organes de voisinage.",
		"aftercare": "Surveillance post-anesthésie; reprise progressive de l'alimentation.",
		"duration": "Variable selon le geste, souvent 20-40 minutes (hors réveil).",
		"risks": ["Risques liés à l'anesthésie", "Risque faible de saignement ou perforation selon le geste"],
		"documents": [],
	},
	{
		"slug": "catheterisme-biliaire",
		"title": "Cathétérisme biliaire",
		"image": "/static/img/exams/catheterisme-biliaire.jpg",
		"description": "Interventions endoscopiques de la voie biliaire.",
		"indications": ["Calculs biliaires", "Sténoses biliaires"],
		"preparation": "Jeûne strict; bilan sanguin de coagulation selon protocole.",
		"procedure": "Geste endoscopique (type CPRE) pour extraire calculs ou poser une prothèse.",
		"aftercare": "Surveillance hospitalière courte; consignes de reprise alimentaire.",
		"duration": "30 à 60 minutes selon complexité (hors surveillance).",
		"risks": ["Pancréatite post-CPRE (rare mais surveillée)", "Saignement ou infection (faible fréquence)"],
		"documents": [],
	},
	{
		"slug": "maladies-anus",
		"title": "Maladies de l'anus",
		"image": "/static/img/exams/maladies-anus.jpg",
		"description": "Prise en charge proctologique.",
		"indications": ["Douleurs, saignements, fissure, hémorroïdes"],
		"preparation": "Souvent sans préparation; lavement possible selon l'examen.",
		"procedure": "Consultation et examen proctologique; gestes simples si indiqué.",
		"aftercare": "Hygiène locale, soins prescrits, surveillance des symptômes.",
		"duration": "Consultation de 15-20 minutes; gestes simples immédiatement réalisables.",
		"risks": ["Inconfort transitoire local", "Risques minimes pour les gestes simples (saignement local)"],
		"documents": [],
	},
	{
		"slug": "nutrition",
		"title": "Nutrition",
		"image": "/static/img/exams/nutrition.jpg",
		"description": "Conseils nutritionnels adaptés.",
		"indications": ["Surpoids, diabète, syndrome métabolique", "Troubles digestifs fonctionnels"],
		"preparation": "Carnet alimentaire ou bilan biologique utile selon le motif.",
		"procedure": "Consultation dédiée avec plan alimentaire personnalisé.",
		"aftercare": "Suivi régulier pour adapter les objectifs et surveiller les bilans.",
		"duration": "Consultation de 20-30 minutes.",
		"risks": ["Aucun risque spécifique"],
		"documents": [],
	},
	{
		"slug": "explorations-fonctionnelles",
		"title": "Explorations fonctionnelles",
		"image": "/static/img/exams/explorations-fonctionnelles.jpg",
		"description": "Bilans digestifs et fonctionnels.",
		"indications": ["Troubles du transit", "Suspicion de malabsorption", "pH-métrie, manométrie"],
		"preparation": "Consignes spécifiques selon l'examen (jeûne, arrêt de traitements).",
		"procedure": "Tests fonctionnels ciblés (pH-métrie, manométrie, tests respiratoires).",
		"aftercare": "Reprise normale sauf consigne contraire; résultats expliqués en consultation.",
		"duration": "Variable selon le test (15 à 60 minutes).",
		"risks": ["Gêne transitoire selon le test (sonde nasale, etc.)"],
		"documents": [],
	},
]


BLOG_POSTS = [
	{
		"slug": "fibres-et-microbiote",
		"title": "Fibres et microbiote : pourquoi en manger ?",
		"date": "15 décembre 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Les fibres nourrissent votre microbiote et régulent le transit. Comment les intégrer progressivement ?",
		"content": "Les fibres solubles et insolubles soutiennent la flore, limitent le pic glycémique et régulent le transit. Augmentez-les progressivement, buvez suffisamment, et consultez si douleurs ou ballonnements persistants.",
	},
	{
		"slug": "diarrhee-chronique",
		"title": "Diarrhée chronique : quand consulter ?",
		"date": "30 novembre 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Plus de 3 semaines de diarrhée : signes d'alerte, bilans et examens utiles.",
		"content": "Une diarrhée qui dure nécessite un avis médical. Signes d'alerte : fièvre, sang dans les selles, amaigrissement, douleurs abdominales. Bilan sanguin, coproculture, calprotectine ou coloscopie peuvent être proposés selon le contexte.",
	},
	{
		"slug": "reflux-enceinte",
		"title": "Reflux chez la femme enceinte : gestes simples",
		"date": "12 novembre 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Adapter les repas, surélever la tête du lit, traitements compatibles : les bons réflexes.",
		"content": "Fractionnez les repas, évitez les aliments acides, café, épices fortes. Surélevez la tête du lit et attendez 2-3h avant de vous allonger. Un traitement peut être proposé si les mesures hygiéno-diététiques ne suffisent pas.",
	},
	{
		"slug": "foie-gras",
		"title": "Foie gras non alcoolique : prévenir et suivre",
		"date": "20 octobre 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Alimentation, activité physique et suivi biologique pour limiter la progression.",
		"content": "Le foie gras non alcoolique repose sur une alimentation équilibrée, une perte de poids progressive, l'activité physique et le suivi des enzymes hépatiques. Consultez pour adapter les examens (fibroscan, échographie).",
	},
	{
		"slug": "hydratation-digestion",
		"title": "L'eau, alliée de votre digestion",
		"date": "10 octobre 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Boire suffisamment d'eau facilite le transit et l'absorption des nutriments. Visez 1,5L par jour.",
		"content": "L'eau aide à dissoudre les graisses et les fibres solubles, permettant un passage plus facile des selles. En cas de constipation, les eaux riches en magnésium peuvent aider.",
	},
	{
		"slug": "manger-lentement",
		"title": "Pourquoi faut-il manger lentement ?",
		"date": "05 octobre 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "La digestion commence dans la bouche. Mâcher réduit le travail de l'estomac et les ballonnements.",
		"content": "Prenez le temps de mastiquer. Cela permet de mieux imprégner les aliments de salive (enzymes), d'envoyer des signaux de satiété au cerveau et d'éviter d'avaler de l'air (aérophagie).",
	},
	{
		"slug": "probiotiques-naturels",
		"title": "Les meilleures sources de probiotiques",
		"date": "28 septembre 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Yaourts, choucroute, kéfir : ces aliments fermentés enrichissent votre flore intestinale.",
		"content": "Les probiotiques sont des bactéries vivantes bénéfiques. Intégrez régulièrement des aliments fermentés comme le yaourt, le kéfir, la choucroute ou le miso pour diversifier votre microbiote.",
	},
	{
		"slug": "aliments-ultra-transformes",
		"title": "Évitez les aliments ultra-transformés",
		"date": "20 septembre 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Additifs, sucres cachés et mauvaises graisses perturbent l'équilibre digestif.",
		"content": "Ces aliments contiennent souvent des émulsifiants et des conservateurs qui peuvent altérer la barrière intestinale et favoriser l'inflammation. Privilégiez les produits bruts et cuisinez maison.",
	},
	{
		"slug": "sommeil-microbiote",
		"title": "Le sommeil influence votre ventre",
		"date": "15 septembre 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Un manque de sommeil peut perturber le microbiote et augmenter les envies de sucre.",
		"content": "Le rythme circadien régule aussi la digestion. Un sommeil irrégulier ou insuffisant peut modifier la composition de la flore intestinale et favoriser la prise de poids ou les troubles fonctionnels.",
	},
	{
		"slug": "stress-ventre",
		"title": "Le stress et vos intestins",
		"date": "10 septembre 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Le cerveau et le ventre sont connectés. Le stress peut déclencher douleurs et troubles du transit.",
		"content": "L'axe intestin-cerveau est bidirectionnel. Le stress chronique peut accélérer ou ralentir le transit et augmenter la sensibilité viscérale. La relaxation, le yoga ou la sophrologie peuvent aider.",
	},
	{
		"slug": "gingembre-digestion",
		"title": "Le gingembre contre les nausées",
		"date": "05 septembre 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Une racine reconnue pour apaiser l'estomac et stimuler la digestion.",
		"content": "Le gingembre est efficace contre les nausées (grossesse, mal des transports) et aide à la vidange gastrique. Consommez-le frais, en infusion ou râpé dans vos plats.",
	},
	{
		"slug": "activite-physique",
		"title": "Bouger pour mieux digérer",
		"date": "01 septembre 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "La marche et le sport stimulent la motricité de l'intestin et réduisent la constipation.",
		"content": "L'activité physique régulière renforce la sangle abdominale et masse naturellement les intestins, favorisant un transit régulier. Évitez cependant le sport intense juste après un repas copieux.",
	},
	{
		"slug": "sel-sante",
		"title": "Réduire le sel pour votre santé",
		"date": "25 août 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "L'excès de sel favorise l'hypertension et peut irriter la muqueuse gastrique.",
		"content": "Une consommation excessive de sel est un facteur de risque pour l'estomac et le système cardiovasculaire. Utilisez des herbes, des épices et des aromates pour donner du goût sans saler.",
	},
	{
		"slug": "fodmaps-intro",
		"title": "Comprendre les FODMAPs",
		"date": "20 août 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Ces sucres fermentescibles peuvent causer ballonnements et douleurs chez les personnes sensibles.",
		"content": "FODMAPs signifie Fermentable Oligo-, Di-, Mono-saccharides And Polyols. En cas de syndrome de l'intestin irritable, un régime pauvre en FODMAPs (sous suivi diététique) peut soulager les symptômes.",
	},
	{
		"slug": "alcool-foie",
		"title": "L'alcool et votre foie",
		"date": "15 août 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Même une consommation modérée peut impacter le foie. Des jours sans alcool sont essentiels.",
		"content": "Le foie métabolise l'alcool mais cela produit des substances toxiques. Pour préserver votre foie, respectez les recommandations (max 2 verres/jour, pas tous les jours) et faites des pauses.",
	},
	{
		"slug": "tabac-estomac",
		"title": "Le tabac et l'estomac",
		"date": "10 août 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Fumer augmente le risque de reflux, d'ulcères et de cancers digestifs.",
		"content": "Le tabac affaiblit le sphincter œsophagien (reflux), diminue la production de mucus protecteur dans l'estomac et retarde la cicatrisation des ulcères. L'arrêt est toujours bénéfique.",
	},
	{
		"slug": "fibres-types",
		"title": "Fibres solubles vs insolubles",
		"date": "05 août 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Connaître la différence pour adapter son alimentation selon son transit.",
		"content": "Les fibres solubles (avoine, fruits, légumineuses) forment un gel doux, bon pour la diarrhée et le cholestérol. Les insolubles (blé complet, son) accélèrent le transit mais peuvent irriter les intestins sensibles.",
	},
	{
		"slug": "repas-soir",
		"title": "Dîner léger pour mieux dormir",
		"date": "01 août 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Un repas trop riche le soir peut perturber le sommeil et favoriser le reflux.",
		"content": "La digestion demande de l'énergie et augmente la température corporelle. Manger gras ou copieux tardivement retarde l'endormissement et favorise les remontées acides nocturnes.",
	},
	{
		"slug": "cafe-digestion",
		"title": "Le café : ami ou ennemi ?",
		"date": "25 juillet 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Il stimule le transit mais peut irriter l'estomac et favoriser le reflux.",
		"content": "La caféine stimule la motricité colique (effet laxatif) mais aussi la sécrétion acide de l'estomac. À limiter en cas de brûlures d'estomac ou de diarrhée.",
	},
	{
		"slug": "legumineuses-digestion",
		"title": "Mieux digérer les légumineuses",
		"date": "20 juillet 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Trempage et cuisson adaptée pour profiter de leurs bienfaits sans les gaz.",
		"content": "Lentilles, pois chiches et haricots sont excellents pour la santé. Pour limiter les flatulences, faites-les tremper longtemps, rincez-les bien et cuisez-les avec du bicarbonate ou de la sarriette.",
	},
	{
		"slug": "intolerance-lactose",
		"title": "Intolérance au lactose : que faire ?",
		"date": "15 juillet 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Pas besoin de tout supprimer. Les fromages affinés et les yaourts sont souvent tolérés.",
		"content": "L'intolérance est due au manque de lactase. Testez votre tolérance : souvent, de petites quantités ou des produits laitiers fermentés (yaourts, fromages durs) passent très bien.",
	},
	{
		"slug": "gluten-verite",
		"title": "Le gluten : faut-il l'arrêter ?",
		"date": "10 juillet 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Inutile de l'exclure sans diagnostic de maladie cœliaque ou de sensibilité avérée.",
		"content": "Le régime sans gluten est contraignant et peut être carencé. Si vous suspectez un problème, consultez pour un dépistage de la maladie cœliaque avant d'arrêter le gluten.",
	},
	{
		"slug": "couleurs-assiette",
		"title": "Mettez de la couleur dans l'assiette",
		"date": "05 juillet 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "La variété des végétaux garantit un apport diversifié en antioxydants et vitamines.",
		"content": "Chaque couleur de fruit ou légume correspond souvent à des nutriments spécifiques (lycopène rouge, bêta-carotène orange...). Varier les couleurs protège votre système digestif et votre santé globale.",
	},
	{
		"slug": "ecouter-faim",
		"title": "Écouter sa faim et sa satiété",
		"date": "01 juillet 2025",
		"author": "Jean-Ariel Bronstein",
		"excerpt": "Manger selon ses besoins évite la surcharge pondérale et digestive.",
		"content": "Apprenez à reconnaître la vraie faim (creux à l'estomac) de l'envie de manger (émotionnelle). Arrêtez-vous quand vous n'avez plus faim pour ne pas surcharger votre estomac.",
	},
]


PATHOLOGIES = [
	{
		"slug": "gastro-enterite",
		"title": "Gastro-entérite",
		"image": "/static/img/pathologies/gastro-enterite.jpg",
		"summary": "Nausées, vomissements, diarrhée : comment se réhydrater et surveiller ?",
		"symptoms": ["Nausées, vomissements", "Diarrhée aiguë", "Crampes abdominales"],
		"emergency": "Consultez en urgence si fièvre élevée, sang dans les selles, signes de déshydratation ou douleurs importantes.",
		"exams": ["Bilan sanguin si fièvre ou terrain fragile", "Coproculture selon contexte"],
		"treatments": ["Réhydratation orale fractionnée", "Régime pauvre en fibres et gras", "Antalgiques adaptés"],
		"advice": ["Boire en petites quantités régulières", "Surveiller la fièvre", "Consulter si symptômes > 48h"],
		"prevention": ["Hygiène des mains", "Cuisson suffisante des aliments"],
		"tags": ["diarrhee", "vomissements", "fièvre"],
	},
	{
		"slug": "brulure-estomac",
		"title": "Brûlures d'estomac / reflux",
		"image": "/static/img/pathologies/brulure-estomac.jpg",
		"summary": "Sensation de brûlure rétro-sternale, remontées acides, gêne après les repas.",
		"symptoms": ["Brûlures rétro-sternales", "Remontées acides", "Toux nocturne", "Gêne en position allongée"],
		"emergency": "Consultez rapidement si douleurs thoraciques atypiques, dysphagie, amaigrissement, anémie.",
		"exams": ["Gastroscopie si signes d'alarme", "pH-métrie selon indications"],
		"treatments": ["Mesures hygiéno-diététiques", "Inhibiteurs de pompe à protons si besoin"],
		"advice": ["Surélever la tête du lit", "Éviter repas copieux et tardifs", "Limiter alcool, café, tabac"],
		"prevention": ["Poids stable", "Repas fractionnés"],
		"tags": ["brulure", "reflux", "nausées"],
	},
	{
		"slug": "gastrite",
		"title": "Gastrite",
		"image": "/static/img/pathologies/gastrite.jpg",
		"summary": "Inflammation de la muqueuse de l'estomac : douleurs, brûlures, inconfort post-prandial.",
		"symptoms": ["Douleurs épigastriques", "Brûlures", "Nausées"],
		"emergency": "Consultez si vomissements sanglants, méléna, anémie ou perte de poids.",
		"exams": ["Gastroscopie si symptômes persistants", "Recherche H. pylori"],
		"treatments": ["Traitement de l'acidité", "Éradication H. pylori si présent"],
		"advice": ["Éviter AINS/aspirine sans avis", "Limiter alcool et tabac"],
		"prevention": ["Prudence AINS", "Repas légers"],
		"tags": ["douleur estomac", "nausées"],
	},
	{
		"slug": "cancer-estomac",
		"title": "Cancer de l'estomac",
		"image": "/static/img/pathologies/cancer-estomac.jpg",
		"summary": "Signes d'alerte et examens de diagnostic.",
		"symptoms": ["Douleurs hautes", "Perte de poids", "Anémie", "Difficultés à avaler"],
		"emergency": "Consultez rapidement pour amaigrissement, vomissements sanglants, méléna.",
		"exams": ["Gastroscopie avec biopsies", "Scanner/IRM selon bilan"],
		"treatments": ["Prise en charge multidisciplinaire", "Chirurgie, endoscopie, oncologie"],
		"advice": ["Arrêt tabac", "Suivi régulier"],
		"prevention": ["Surveillance si facteurs de risque"],
		"tags": ["amaigrissement", "douleur estomac"],
	},
	{
		"slug": "diarrhee-chronique",
		"title": "Diarrhée chronique",
		"image": "/static/img/pathologies/diarrhee-chronique.jpg",
		"summary": "Plus de 3 semaines de diarrhée : bilan adapté, signes d'alerte.",
		"symptoms": ["Selles liquides > 3 semaines", "Ballonnements", "Crampes"],
		"emergency": "Consultez si sang dans les selles, fièvre, amaigrissement, douleurs importantes.",
		"exams": ["Bilan sanguin", "Coproculture", "Coloscopie selon contexte"],
		"treatments": ["Réhydratation", "Adaptation alimentaire", "Traitement étiologique"],
		"advice": ["Surveiller les signes de déshydratation", "Noter le lien avec aliments/medicaments"],
		"prevention": ["Hygiène alimentaire", "Suivi médical"],
		"tags": ["diarrhee", "fièvre", "sang selles"],
	},
	{
		"slug": "reflux-enceinte",
		"title": "Reflux de la femme enceinte",
		"image": "/static/img/pathologies/reflux-enceinte.jpg",
		"summary": "Adapter l'alimentation et la position pour limiter les reflux pendant la grossesse.",
		"symptoms": ["Brûlures", "Regurgitations", "Gêne nocturne"],
		"emergency": "Consultez si douleurs thoraciques atypiques ou perte de poids.",
		"exams": ["Examens limités pendant la grossesse; avis médical"],
		"treatments": ["Mesures hygiéno-diététiques", "Traitement compatible grossesse si besoin"],
		"advice": ["Petits repas fréquents", "Surélever la tête du lit", "Éviter allongement post-repas"],
		"prevention": ["Alimentation fractionnée"],
		"tags": ["reflux", "grossesse"],
	},
	{
		"slug": "foie-gras",
		"title": "Foie gras non alcoolique",
		"image": "/static/img/pathologies/foie-gras.jpg",
		"summary": "Prévention de la progression vers la fibrose : mode de vie et suivi.",
		"symptoms": ["Souvent asymptomatique", "Fatigue", "Inconfort abdominal"],
		"emergency": "Consultez si douleurs importantes, ictère ou bilan hépatique très perturbé.",
		"exams": ["Bilan hépatique", "Échographie", "Fibroscan selon indications"],
		"treatments": ["Perte de poids progressive", "Activité physique", "Suivi médical"],
		"advice": ["Alimentation équilibrée", "Limiter sucres et alcool"],
		"prevention": ["Activité physique régulière", "Suivi biologique"],
		"tags": ["foie", "bilan hepatique"],
	},
	{
		"slug": "lithiase-biliaire",
		"title": "Calculs biliaires",
		"image": "/static/img/pathologies/lithiase-biliaire.jpg",
		"summary": "Présence de calculs dans la vésicule : colique hépatique et complications.",
		"symptoms": ["Douleur brutale sous les côtes à droite", "Irradiation vers l'épaule ou le dos", "Nausées ou vomissements"],
		"emergency": "Consultez en urgence si fièvre, frissons, jaunisse ou douleur persistante > 6h.",
		"exams": ["Échographie abdominale", "Bilan hépatique"],
		"treatments": ["Antalgiques et antispasmodiques", "Chirurgie (cholécystectomie) si symptomatique"],
		"advice": ["Éviter les repas très gras", "Consulter si récidive"],
		"prevention": ["Alimentation équilibrée", "Éviter le jeûne prolongé"],
		"tags": ["douleur abdominale", "vésicule", "colique"],
	},
	{
		"slug": "maladie-crohn",
		"title": "Maladie de Crohn",
		"image": "/static/img/pathologies/maladie-crohn.jpg",
		"summary": "Maladie inflammatoire chronique pouvant toucher tout le tube digestif.",
		"symptoms": ["Douleurs abdominales", "Diarrhée chronique", "Perte de poids", "Fatigue"],
		"emergency": "Consultez si douleurs intenses, fièvre, arrêt du transit ou sang abondant.",
		"exams": ["Coloscopie avec biopsies", "Entéro-IRM", "Bilan sanguin (CRP)"],
		"treatments": ["Anti-inflammatoires", "Immunosuppresseurs", "Biothérapies"],
		"advice": ["Arrêt strict du tabac", "Suivi régulier même en rémission"],
		"prevention": ["Arrêt du tabac"],
		"tags": ["diarrhee", "douleur abdominale", "MICI"],
	},
	{
		"slug": "rch",
		"title": "Rectocolite hémorragique (RCH)",
		"image": "/static/img/pathologies/rch.jpg",
		"summary": "Inflammation chronique du rectum et du côlon.",
		"symptoms": ["Diarrhée sanglante", "Faux besoins", "Douleurs rectales"],
		"emergency": "Consultez si fièvre, selles très fréquentes (>6/j) ou saignements importants.",
		"exams": ["Rectosigmoïdoscopie ou coloscopie", "Calprotectine fécale"],
		"treatments": ["5-ASA (suppositoires/comprimés)", "Corticoïdes", "Biothérapies"],
		"advice": ["Suivre le traitement d'entretien", "Surveiller les selles"],
		"prevention": ["Suivi médical régulier"],
		"tags": ["sang selles", "diarrhee", "MICI"],
	},
	{
		"slug": "syndrome-intestin-irritable",
		"title": "Syndrome de l'intestin irritable",
		"image": "/static/img/pathologies/syndrome-intestin-irritable.jpg",
		"summary": "Trouble fonctionnel fréquent associant douleurs et troubles du transit.",
		"symptoms": ["Ballonnements", "Douleurs soulagées par les selles", "Alternance diarrhée/constipation"],
		"emergency": "Pas d'urgence vitale, mais consultez si symptômes nouveaux après 50 ans.",
		"exams": ["Bilan sanguin pour éliminer autre cause", "Coloscopie si signes d'alarme"],
		"treatments": ["Antispasmodiques", "Régime pauvre en FODMAPs", "Probiotiques"],
		"advice": ["Identifier les aliments déclencheurs", "Gestion du stress"],
		"prevention": ["Alimentation équilibrée", "Activité physique"],
		"tags": ["douleur abdominale", "ballonnements", "constipation"],
	},
	{
		"slug": "ulcere-gastrique",
		"title": "Ulcère gastrique",
		"image": "/static/img/pathologies/ulcere-gastrique.jpg",
		"summary": "Plaie profonde dans la paroi de l'estomac.",
		"symptoms": ["Douleur type crampe à l'estomac", "Calmée ou aggravée par les repas"],
		"emergency": "Consultez en urgence si vomissements de sang ou selles noires.",
		"exams": ["Gastroscopie (indispensable)", "Biopsies"],
		"treatments": ["IPP (Inhibiteurs de la pompe à protons)", "Éradication H. pylori"],
		"advice": ["Arrêt tabac et alcool", "Éviter l'automédication par anti-inflammatoires"],
		"prevention": ["Prudence avec les AINS"],
		"tags": ["douleur estomac", "ulcere"],
	},
	{
		"slug": "pancreatite-aigue",
		"title": "Pancréatite aiguë",
		"image": "/static/img/pathologies/pancreatite-aigue.jpg",
		"summary": "Inflammation brutale du pancréas, souvent liée à un calcul ou à l'alcool.",
		"symptoms": ["Douleur violente en barre au creux de l'estomac", "Irradiation dans le dos", "Vomissements"],
		"emergency": "Urgence médicale : hospitalisation nécessaire.",
		"exams": ["Prise de sang (Lipase)", "Scanner abdominal"],
		"treatments": ["Jeûne", "Perfusion", "Antalgiques puissants"],
		"advice": ["Arrêt alcool", "Traitement des calculs biliaires ensuite"],
		"prevention": ["Modération alcool", "Surveillance lithiase"],
		"tags": ["douleur abdominale", "pancreas", "urgence"],
	},
	{
		"slug": "cirrhose",
		"title": "Cirrhose du foie",
		"image": "/static/img/pathologies/cirrhose.jpg",
		"summary": "Stade avancé de fibrose hépatique, irréversible mais stabilisable.",
		"symptoms": ["Souvent asymptomatique au début", "Puis fatigue, jaunisse, ascite"],
		"emergency": "Consultez si vomissements de sang, confusion ou fièvre.",
		"exams": ["Bilan hépatique", "Échographie", "Fibroscan"],
		"treatments": ["Traitement de la cause (alcool, virus)", "Surveillance complications"],
		"advice": ["Arrêt total alcool", "Vaccination hépatites"],
		"prevention": ["Dépistage hépatites", "Lutte contre l'alcoolisme"],
		"tags": ["foie", "jaunisse", "fatigue"],
	},
	{
		"slug": "hepatite-b",
		"title": "Hépatite B",
		"image": "/static/img/pathologies/hepatite-b.jpg",
		"summary": "Infection virale du foie, transmissible par le sang et les rapports sexuels.",
		"symptoms": ["Souvent silencieuse", "Parfois fatigue, nausées, jaunisse"],
		"emergency": "Consultez pour dépistage ou suivi.",
		"exams": ["Sérologie virale", "Bilan hépatique"],
		"treatments": ["Antiviraux si nécessaire", "Vaccination de l'entourage"],
		"advice": ["Protection rapports sexuels", "Ne pas partager rasoirs/brosses à dents"],
		"prevention": ["Vaccination (très efficace)"],
		"tags": ["foie", "virus", "MST"],
	},
	{
		"slug": "hepatite-c",
		"title": "Hépatite C",
		"image": "/static/img/pathologies/hepatite-c.jpg",
		"summary": "Infection virale du foie, transmissible par le sang, guérissable aujourd'hui.",
		"symptoms": ["Asymptomatique le plus souvent", "Fatigue chronique"],
		"emergency": "Pas d'urgence, mais nécessite un traitement pour éviter la cirrhose.",
		"exams": ["Sérologie VHC", "PCR virale"],
		"treatments": ["Antiviraux directs (guérison > 95%)"],
		"advice": ["Dépistage si facteurs de risque (transfusion avant 1992, toxicomanie)"],
		"prevention": ["Matériel à usage unique"],
		"tags": ["foie", "virus"],
	},
	{
		"slug": "hemochromatose",
		"title": "Hémochromatose",
		"image": "/static/img/pathologies/hemochromatose.jpg",
		"summary": "Maladie génétique entraînant une surcharge en fer dans l'organisme.",
		"symptoms": ["Fatigue", "Douleurs articulaires", "Teint grisâtre"],
		"emergency": "Non, mais diagnostic précoce important.",
		"exams": ["Ferritine", "Coefficient de saturation de la transferrine", "Test génétique"],
		"treatments": ["Saignées régulières (phlébotomies)"],
		"advice": ["Éviter compléments en fer et vitamine C", "Limiter alcool"],
		"prevention": ["Dépistage familial"],
		"tags": ["foie", "fatigue", "genetique"],
	},
	{
		"slug": "maladie-coeliaque",
		"title": "Maladie cœliaque",
		"image": "/static/img/pathologies/maladie-coeliaque.jpg",
		"summary": "Intolérance immunitaire au gluten (blé, orge, seigle).",
		"symptoms": ["Diarrhée", "Ballonnements", "Anémie", "Amaigrissement"],
		"emergency": "Non, mais nécessite un régime strict à vie.",
		"exams": ["Anticorps anti-transglutaminase", "Gastroscopie avec biopsies duodénales"],
		"treatments": ["Régime sans gluten strict et à vie"],
		"advice": ["Apprendre à lire les étiquettes", "Attention aux contaminations croisées"],
		"prevention": ["Aucune (prédisposition génétique)"],
		"tags": ["diarrhee", "anemie", "gluten"],
	},
	{
		"slug": "diverticulose",
		"title": "Diverticulose colique",
		"image": "/static/img/pathologies/diverticulose.jpg",
		"summary": "Présence de petites poches (diverticules) sur la paroi du côlon.",
		"symptoms": ["Asymptomatique le plus souvent", "Parfois troubles du transit"],
		"emergency": "Non, sauf complication (diverticulite).",
		"exams": ["Coloscopie (découverte souvent fortuite)", "Scanner si douleur"],
		"treatments": ["Régime riche en fibres", "Hydratation"],
		"advice": ["Lutter contre la constipation"],
		"prevention": ["Manger des fibres"],
		"tags": ["colon", "constipation"],
	},
	{
		"slug": "diverticulite",
		"title": "Diverticulite",
		"image": "/static/img/pathologies/diverticulite.jpg",
		"summary": "Infection d'un diverticule : la 'sigmoïdite'.",
		"symptoms": ["Douleur en bas à gauche du ventre", "Fièvre", "Troubles du transit"],
		"emergency": "Consultez rapidement (risque d'abcès ou péritonite).",
		"exams": ["Scanner abdominal (examen de référence)", "Bilan sanguin"],
		"treatments": ["Antibiotiques", "Régime sans résidus", "Parfois hospitalisation"],
		"advice": ["Reprise progressive des fibres après guérison"],
		"prevention": ["Traiter la constipation"],
		"tags": ["douleur abdominale", "fievre", "colon"],
	},
	{
		"slug": "polypes-colon",
		"title": "Polypes du côlon",
		"image": "/static/img/pathologies/polypes-colon.jpg",
		"summary": "Excroissances sur la paroi du côlon, précurseurs possibles du cancer.",
		"symptoms": ["Généralement aucun", "Parfois sang dans les selles"],
		"emergency": "Non, mais doivent être retirés par prévention.",
		"exams": ["Coloscopie (diagnostic et traitement)"],
		"treatments": ["Ablation endoscopique (polypectomie)"],
		"advice": ["Suivre le rythme des coloscopies de contrôle"],
		"prevention": ["Dépistage organisé (test immunologique)"],
		"tags": ["colon", "prevention", "sang selles"],
	},
	{
		"slug": "cancer-colon",
		"title": "Cancer colorectal",
		"image": "/static/img/pathologies/cancer-colon.jpg",
		"summary": "Tumeur maligne du côlon ou du rectum.",
		"symptoms": ["Sang dans les selles", "Modification du transit récente", "Anémie"],
		"emergency": "Consultez rapidement pour diagnostic.",
		"exams": ["Coloscopie avec biopsies", "Scanner TAP"],
		"treatments": ["Chirurgie", "Chimiothérapie", "Radiothérapie (rectum)"],
		"advice": ["Dépistage dès 50 ans ou avant si antécédents"],
		"prevention": ["Test immunologique tous les 2 ans (50-74 ans)"],
		"tags": ["sang selles", "cancer", "colon"],
	},
	{
		"slug": "cancer-pancreas",
		"title": "Cancer du pancréas",
		"image": "/static/img/pathologies/cancer-pancreas.jpg",
		"summary": "Tumeur du pancréas, souvent diagnostiquée tardivement.",
		"symptoms": ["Jaunisse indolore", "Amaigrissement rapide", "Douleur solaire"],
		"emergency": "Consultez rapidement devant ces signes.",
		"exams": ["Scanner abdominal", "Echo-endoscopie"],
		"treatments": ["Chirurgie (si possible)", "Chimiothérapie"],
		"advice": ["Arrêt tabac (facteur de risque majeur)"],
		"prevention": ["Surveillance si pancréatite chronique ou génétique"],
		"tags": ["jaunisse", "amaigrissement", "pancreas"],
	},
	{
		"slug": "cancer-oesophage",
		"title": "Cancer de l'œsophage",
		"image": "/static/img/pathologies/cancer-oesophage.jpg",
		"summary": "Tumeur de l'œsophage liée souvent au tabac/alcool ou au reflux.",
		"symptoms": ["Blocage alimentaire (dysphagie)", "Amaigrissement"],
		"emergency": "Consultez dès l'apparition d'une gêne à la déglutition.",
		"exams": ["Gastroscopie", "Scanner"],
		"treatments": ["Radio-chimiothérapie", "Chirurgie"],
		"advice": ["Arrêt tabac et alcool"],
		"prevention": ["Surveillance endobrachyoesophage (EBO)"],
		"tags": ["dysphagie", "amaigrissement", "oesophage"],
	},
	{
		"slug": "achalasie",
		"title": "Achalasie",
		"image": "/static/img/pathologies/achalasie.jpg",
		"summary": "Trouble moteur de l'œsophage empêchant l'ouverture du sphincter inférieur.",
		"symptoms": ["Blocage des aliments et liquides", "Régurgitations non acides"],
		"emergency": "Non, mais altère la qualité de vie et la nutrition.",
		"exams": ["Manométrie œsophagienne", "Gastroscopie"],
		"treatments": ["Dilatation pneumatique", "Chirurgie (myotomie)"],
		"advice": ["Manger lentement, bien mâcher"],
		"prevention": ["Aucune connue"],
		"tags": ["dysphagie", "oesophage"],
	},
	{
		"slug": "hernie-hiatale",
		"title": "Hernie hiatale",
		"image": "/static/img/pathologies/hernie-hiatale.jpg",
		"summary": "Remontée d'une partie de l'estomac dans le thorax.",
		"symptoms": ["Favorise le reflux (RGO)", "Parfois asymptomatique"],
		"emergency": "Rarement (étranglement exceptionnel).",
		"exams": ["Gastroscopie"],
		"treatments": ["IPP si reflux gênant", "Chirurgie si volumineuse et symptomatique"],
		"advice": ["Éviter de se coucher après le repas"],
		"prevention": ["Éviter le surpoids"],
		"tags": ["reflux", "estomac"],
	},
	{
		"slug": "hemorroides",
		"title": "Hémorroïdes",
		"image": "/static/img/pathologies/hemorroides.jpg",
		"summary": "Dilatation des veines de la zone anale.",
		"symptoms": ["Saignement rouge vif", "Douleur", "Boule à l'anus"],
		"emergency": "Consultez si douleur insupportable (thrombose) ou saignement abondant.",
		"exams": ["Examen proctologique", "Anuscopie"],
		"treatments": ["Crèmes/suppositoires", "Traitements instrumentaux", "Chirurgie"],
		"advice": ["Lutter contre la constipation", "Éviter les épices"],
		"prevention": ["Régime riche en fibres"],
		"tags": ["anus", "douleur", "sang"],
	},
	{
		"slug": "fissure-anale",
		"title": "Fissure anale",
		"image": "/static/img/pathologies/fissure-anale.jpg",
		"summary": "Petite déchirure de la peau de l'anus, très douloureuse.",
		"symptoms": ["Douleur intense pendant et après la selle", "Saignement sur le papier"],
		"emergency": "Non, mais très invalidant.",
		"exams": ["Examen proctologique doux"],
		"treatments": ["Laxatifs", "Crèmes cicatrisantes", "Chirurgie si chronique"],
		"advice": ["Ne pas se retenir d'aller à la selle"],
		"prevention": ["Éviter la constipation"],
		"tags": ["anus", "douleur"],
	},
	{
		"slug": "abces-anal",
		"title": "Abcès et fistule anale",
		"image": "/static/img/pathologies/abces-anal.jpg",
		"summary": "Infection d'une glande anale créant une collection de pus.",
		"symptoms": ["Douleur pulsatile", "Gonflement rouge et chaud", "Fièvre"],
		"emergency": "Oui, nécessite une incision chirurgicale rapide.",
		"exams": ["Examen clinique", "IRM périnéale parfois"],
		"treatments": ["Chirurgie (mise à plat ou drainage)"],
		"advice": ["Consulter dès l'apparition d'une boule douloureuse"],
		"prevention": ["Aucune spécifique"],
		"tags": ["anus", "douleur", "urgence"],
	},
	{
		"slug": "condylomes",
		"title": "Condylomes anaux",
		"image": "/static/img/pathologies/condylomes.jpg",
		"summary": "Verrues génitales dues au virus HPV (Papillomavirus).",
		"symptoms": ["Petites excroissances indolores", "Démangeaisons"],
		"emergency": "Non, mais contagieux.",
		"exams": ["Anuscopie haute résolution"],
		"treatments": ["Destruction locale (laser, électrocoagulation)"],
		"advice": ["Dépistage des partenaires", "Surveillance régulière"],
		"prevention": ["Vaccination HPV", "Préservatif"],
		"tags": ["anus", "MST", "virus"],
	},
	{
		"slug": "constipation",
		"title": "Constipation chronique",
		"image": "/static/img/pathologies/constipation.jpg",
		"summary": "Selles rares (<3/semaine) ou difficiles à évacuer.",
		"symptoms": ["Efforts de poussée", "Sensation d'évacuation incomplète", "Ballonnements"],
		"emergency": "Consultez si arrêt total des gaz (occlusion) ou douleur brutale.",
		"exams": ["Coloscopie (éliminer un obstacle)", "Temps de transit"],
		"treatments": ["Fibres +++", "Hydratation", "Laxatifs osmotiques"],
		"advice": ["Activité physique", "Aller à la selle à heure fixe"],
		"prevention": ["Boire 1,5L d'eau par jour"],
		"tags": ["constipation", "ventre"],
	},
	{
		"slug": "incontinence-fecale",
		"title": "Incontinence fécale",
		"image": "/static/img/pathologies/incontinence-fecale.jpg",
		"summary": "Perte involontaire de gaz ou de selles.",
		"symptoms": ["Fuites incontrôlées", "Urgenturie fécale"],
		"emergency": "Non, mais impact social majeur.",
		"exams": ["Manométrie anorectale", "Echo-endoscopie anale"],
		"treatments": ["Rééducation périnéale", "Régularisation du transit", "Neuromodulation"],
		"advice": ["Oser en parler au médecin"],
		"prevention": ["Protection du périnée (accouchement)"],
		"tags": ["anus", "incontinence"],
	},
	{
		"slug": "dyspepsie",
		"title": "Dyspepsie fonctionnelle",
		"image": "/static/img/pathologies/dyspepsie.jpg",
		"summary": "Inconfort ou douleur chronique au creux de l'estomac sans lésion visible.",
		"symptoms": ["Lourdeur après repas", "Satiété précoce", "Douleur épigastrique"],
		"emergency": "Non.",
		"exams": ["Gastroscopie (normale)"],
		"treatments": ["IPP", "Prokinétiques", "Relaxation"],
		"advice": ["Manger lentement", "Fractionner les repas"],
		"prevention": ["Éviter repas trop gras"],
		"tags": ["estomac", "digestion"],
	},
	{
		"slug": "sibo",
		"title": "SIBO (Pullulation microbienne)",
		"image": "/static/img/pathologies/sibo.jpg",
		"summary": "Excès de bactéries dans l'intestin grêle (Small Intestinal Bacterial Overgrowth).",
		"symptoms": ["Ballonnements précoces après repas", "Gaz", "Diarrhée"],
		"emergency": "Non.",
		"exams": ["Test respiratoire au glucose/lactulose"],
		"treatments": ["Antibiotiques ciblés", "Régime pauvre en fermentescibles"],
		"advice": ["Éviter le grignotage (laisser le complexe moteur migrant agir)"],
		"prevention": ["Traiter les causes de ralentissement du transit"],
		"tags": ["ballonnements", "intestin"],
	},
	{
		"slug": "ascite",
		"title": "Ascite",
		"image": "/static/img/pathologies/ascite.jpg",
		"summary": "Accumulation de liquide dans l'abdomen, souvent liée à une cirrhose.",
		"symptoms": ["Augmentation du volume du ventre", "Prise de poids rapide"],
		"emergency": "Consultez rapidement, surtout si fièvre ou douleur.",
		"exams": ["Ponction d'ascite", "Échographie"],
		"treatments": ["Régime sans sel", "Diurétiques", "Ponctions évacuatrices"],
		"advice": ["Pesée régulière", "Respect strict du régime sans sel"],
		"prevention": ["Traitement de la maladie du foie"],
		"tags": ["foie", "ventre"],
	},
	{
		"slug": "kyste-biliiare",
		"title": "Kyste biliaire",
		"image": "/static/img/pathologies/kyste-biliaire.jpg",
		"summary": "Poche de liquide dans le foie, souvent bénigne.",
		"symptoms": ["Généralement aucun", "Découverte fortuite"],
		"emergency": "Non.",
		"exams": ["Échographie", "Scanner ou IRM pour caractériser"],
		"treatments": ["Abstention thérapeutique le plus souvent", "Surveillance"],
		"advice": ["Pas d'inquiétude si kyste simple typique"],
		"prevention": ["Aucune"],
		"tags": ["foie", "kyste"],
	},
	{
		"slug": "angiome-foie",
		"title": "Angiome du foie",
		"image": "/static/img/pathologies/angiome-foie.jpg",
		"summary": "Tumeur bénigne du foie constituée de vaisseaux sanguins.",
		"symptoms": ["Asymptomatique", "Très fréquent"],
		"emergency": "Non.",
		"exams": ["Échographie (aspect typique)", "IRM si doute"],
		"treatments": ["Aucun traitement nécessaire"],
		"advice": ["Aucun suivi particulier si typique"],
		"prevention": ["Aucune"],
		"tags": ["foie", "tumeur benigne"],
	},
]


GUIDES = [
	{
		"slug": "preparation-coloscopie",
		"title": "Comment se préparer à une coloscopie",
		"summary": "Étapes la veille et le jour J, diète et laxatif.",
		"steps": [
			"Régime pauvre en résidus la veille (précisions sur l'ordonnance).",
			"Boire le laxatif aux horaires indiqués, en fractionnant si besoin.",
			"Hydratation par liquides clairs jusqu'à l'horaire autorisé.",
			"Arriver accompagné si anesthésie; ne pas conduire après l'examen.",
		],
		"pdf": "",
	},
	{
		"slug": "deroulement-fibroscopie",
		"title": "Comment se déroule une fibroscopie",
		"summary": "Durée de l'examen, anesthésie et reprise alimentaire.",
		"steps": [
			"Jeûne de 6h pour solides et 2h pour liquides clairs, sauf consigne différente.",
			"Sédation courte ou anesthésie selon indication; durée d'examen environ 10 minutes.",
			"Surveillance en salle de réveil; reprise alimentaire légère après accord médical.",
			"Ne pas conduire le jour même en cas de sédation/anesthésie.",
		],
		"pdf": "",
	},
	{
		"slug": "anesthesie-endoscopie",
		"title": "Anesthésie pour endoscopie : questions fréquentes",
		"summary": "Sécurité, jeûne, reprise des traitements habituels.",
		"steps": [
			"Respecter le jeûne indiqué; signaler tout traitement (anticoagulant, antiagrégant).",
			"Prendre les traitements autorisés avec une petite gorgée d'eau si prescrit.",
			"Prévoir un accompagnant; ne pas conduire ni signer de documents importants le jour même.",
			"En cas de fièvre ou symptômes la veille, prévenir le secrétariat/anesthésiste.",
		],
		"pdf": "",
	},
	{
		"slug": "apres-examen",
		"title": "Recommandations après l'examen",
		"summary": "Surveillance à domicile, reprise alimentaire, signes d'alerte.",
		"steps": [
			"Repos le jour même en cas d'anesthésie; ne pas conduire.",
			"Reprise alimentaire progressive selon consignes du médecin.",
			"Surveiller l'apparition de douleurs importantes, fièvre, vomissements ou saignements.",
			"Contacter le cabinet ou les urgences en cas de signe d'alerte.",
		],
		"pdf": "",
	},
]


FAQS = [
	{"q": "Dois-je être à jeun avant une endoscopie ?", "a": "Oui, en général 6h sans manger et 2h sans boire de liquide clair, sauf consigne différente."},
	{"q": "Puis-je conduire après une anesthésie ?", "a": "Non, prévoyez un accompagnant. Ne conduisez pas ni ne signez de documents importants le jour même."},
	{"q": "Quels traitements dois-je arrêter avant une coloscopie ?", "a": "Aspirine, anticoagulants ou antiagrégants peuvent nécessiter un ajustement : demandez un avis personnalisé."},
	{"q": "Combien de temps dure une coloscopie ?", "a": "Environ 20 à 30 minutes, plus le temps de préparation et de réveil."},
	{"q": "Quand consulter en urgence ?", "a": "Fièvre élevée, sang dans les selles, douleurs abdominales intenses, vomissements répétés : appelez ou rendez-vous aux urgences."},
	{"q": "Faut-il une ordonnance pour consulter ?", "a": "Il est préférable d'avoir un courrier de votre médecin traitant pour respecter le parcours de soins et être mieux remboursé."},
	{"q": "Le médecin est-il conventionné ?", "a": "Oui, le Dr Bronstein est conventionné et accepte le tiers payant."},
	{"q": "Comment se passe le paiement ?", "a": "Le règlement se fait sur place par chèque, espèces ou carte bancaire. Le tiers payant est possible selon votre couverture."},
	{"q": "Où se garer pour venir au cabinet ?", "a": "Des parkings publics sont disponibles à proximité de l'immeuble Air France (parking Tarahoi ou front de mer)."},
	{"q": "Les enfants sont-ils pris en charge ?", "a": "Le Dr Bronstein reçoit les adultes et adolescents. Pour les jeunes enfants, un pédiatre gastro-entérologue est recommandé."},
	{"q": "Puis-je avoir un arrêt de travail ?", "a": "Un arrêt de travail peut être délivré le jour de l'examen (coloscopie/fibroscopie) si nécessaire."},
	{"q": "Combien de temps avant d'avoir les résultats ?", "a": "Le compte-rendu est remis immédiatement après l'examen. Les résultats de biopsies prennent environ 10 à 15 jours."},
	{"q": "Que faire si j'ai oublié ma préparation ?", "a": "Contactez le secrétariat au plus vite. Une mauvaise préparation peut obliger à annuler et reporter l'examen."},
	{"q": "Le cabinet est-il accessible aux PMR ?", "a": "Oui, l'immeuble dispose d'ascenseurs et est accessible aux personnes à mobilité réduite."},
	{"q": "Puis-je venir accompagné ?", "a": "Oui, c'est même obligatoire pour repartir après une anesthésie générale ou une sédation."},
	{"q": "En quoi consiste une pH-métrie ?", "a": "C'est un examen qui mesure l'acidité dans l'œsophage pendant 24h à l'aide d'une fine sonde nasale, pour diagnostiquer un reflux."},
	{"q": "La pH-métrie est-elle douloureuse ?", "a": "L'examen est peu agréable lors de la pose de la sonde, mais n'est pas douloureux. On s'habitue rapidement à la présence de la sonde."},
	{"q": "Qu'est-ce qu'une vidéocapsule ?", "a": "C'est une gélule contenant une caméra que l'on avale pour explorer l'intestin grêle, zone inaccessible aux endoscopes classiques."},
	{"q": "Peut-on faire une gastroscopie et une coloscopie en même temps ?", "a": "Oui, c'est fréquent. Cela permet de réaliser les deux examens sous la même anesthésie."},
	{"q": "Qu'est-ce que l'Helicobacter pylori ?", "a": "C'est une bactérie présente dans l'estomac qui peut causer gastrites et ulcères. Elle se traite par antibiotiques."},
	{"q": "Le stress peut-il causer des maux de ventre ?", "a": "Oui, le stress influence le système digestif et peut aggraver le syndrome de l'intestin irritable ou les brûlures d'estomac."},
	{"q": "Quels sont les symptômes d'un polype au côlon ?", "a": "La plupart des polypes ne donnent aucun symptôme, d'où l'importance du dépistage par coloscopie avant qu'ils ne dégénèrent."},
	{"q": "Y a-t-il des risques à passer une coloscopie ?", "a": "Les risques (perforation, hémorragie) sont très rares. Le bénéfice du dépistage du cancer colorectal est largement supérieur."},
	{"q": "Quelle alimentation en cas de diverticules ?", "a": "En dehors des crises, une alimentation riche en fibres est recommandée. En cas de crise (diverticulite), un régime sans résidus est prescrit."},
	{"q": "Dois-je arrêter de boire de l'eau avant l'examen ?", "a": "L'arrêt des liquides clairs (eau, thé, café sans lait) est généralement demandé 2 heures avant l'anesthésie."},
]


SYMPTOM_TAGS = {
	"brûlures / reflux": ["brulure-estomac", "reflux-enceinte"],
	"diarrhée": ["gastro-enterite", "diarrhee-chronique"],
	"douleurs hautes": ["gastrite", "brulure-estomac", "cancer-estomac"],
	"foie / bilan hépatique": ["foie-gras"],
	"sang dans les selles": ["diarrhee-chronique"],
}


TEAM = [
	{
		"name": "Dr Jean-Ariel Bronstein",
		"role": "Professeur agrégé du Val-de-Grâce",
		"focus": "Gastro-entérologue, Oncologie digestive, endoscopies interventionnelles, échographie abdominale",
		"contact": "docteur@bronstein.fr",
		"photo": "img/dr-bronstein.jpg",
	},
	{
		"name": "Tania Mauri",
		"role": "Secrétaire médicale",
		"focus": "Accueil, rendez-vous, préparation des examens",
		"contact": "secretaire@bronstein.fr",
		"photo": "img/tania-mauri.jpg",
	},
]


CONTACT = {
	"phones": ["40 81 48 48", "87 37 87 50", "87 345 372"],
	"doctor_email": "docteur@bronstein.fr",
	"secretary_email": "secretaire@bronstein.fr",
	"hospital": {
		"title": "Clinique PAOFAI",
		"address": "BP 40149 — 98713 Papeete, Tahiti",
		"phone": "40 46 18 18",
		"maps": "https://maps.google.com/?q=Clinique+Paofai+Tahiti",
	},
	"consult": {
		"title": "Consultations",
		"address": "Immeuble Air France — rue LAGARDE — 4e étage (en face de GEMO), Papeete",
		"phone": "40 81 48 48 / 87 345 372",
		"maps": "https://maps.google.com/?q=Immeuble+Air+France+Papeete",
	},
	"hours": "Lundi-Vendredi 07:00-17:00 · Samedi 08:30-12:00",
}


HOME_TILES = [
	{
		"title": "Prendre rendez-vous",
		"text": "Téléphone ou formulaire rapide pour planifier une consultation ou une endoscopie.",
		"action": "Appeler le cabinet",
		"link": "tel:+68940814848",
		"variant": "primary",
	},
	{
		"title": "Préparer mon examen",
		"text": "Consignes claires pour coloscopie, fibroscopie et examens digestifs.",
		"action": "Consignes coloscopie",
		"link": "/guides/#preparation-coloscopie",
		"variant": "outline",
	},
	{
		"title": "Conseils digestifs",
		"text": "Reflux, diarrhée chronique, foie gras : que faire avant de consulter ?",
		"action": "Voir les articles",
		"link": "/blog/",
		"variant": "ghost",
	},
]


def home(request):
	context = {
		"hero": {
			"title": "Je viens consulter, comment ça se passe ?",
			"subtitle": "",
			"cta_call": "tel:+68940814848",
			"cta_message": "mailto:bronstein@mail.pf",
		},
		"tiles": HOME_TILES,
		"specialties": EXAMS,
		"blog_posts": BLOG_POSTS,
		"contact": CONTACT,
		"pathologies": PATHOLOGIES,
		"guides": GUIDES,
		"faqs": FAQS[:4],
		"team": TEAM,
	}
	return render(request, "core/home.html", context)


def exam_list(request):
	return render(request, "core/exams.html", {"exams": EXAMS})


def exam_detail(request, slug):
	try:
		exam = next(e for e in EXAMS if e["slug"] == slug)
	except StopIteration as exc:
		raise Http404 from exc

	return render(request, "core/exam_detail.html", {"exam": exam, "exams": EXAMS})


def consultations(request):
	context = {"contact": CONTACT, "team": TEAM}
	return render(request, "core/consultations.html", context)


def pathology_list(request):
	return render(request, "core/pathologies.html", {"pathologies": PATHOLOGIES})


def pathology_detail(request, slug):
	try:
		pathology = next(p for p in PATHOLOGIES if p["slug"] == slug)
	except StopIteration as exc:
		raise Http404 from exc

	return render(
		request,
		"core/pathology_detail.html",
		{"pathology": pathology, "pathologies": PATHOLOGIES},
	)


def guides(request):
	return render(request, "core/guides.html", {"guides": GUIDES})


def symptom_index(request):
	enriched = []
	for label, slugs in SYMPTOM_TAGS.items():
		items = [p for p in PATHOLOGIES if p["slug"] in slugs]
		enriched.append({"label": label, "items": items})
	return render(request, "core/symptoms.html", {"groups": enriched})


def faq(request):
	return render(request, "core/faq.html", {"faqs": FAQS})


def appointment(request):
	context = {
		"contact": CONTACT,
		"cta": {
			"call": "tel:+68940814848",
			"message": f"mailto:{CONTACT['secretary_email']}",
			"doctolib": "https://www.maiia.com/gastro-enterologue-et-hepatologue/98714-papeete/bronstein-jean-ariel",
		},
		"team": TEAM,
	}
	return render(request, "core/appointment.html", context)


def blog_list(request):
	return render(request, "core/blog_list.html", {"posts": BLOG_POSTS})


def blog_detail(request, slug):
	try:
		post = next(p for p in BLOG_POSTS if p["slug"] == slug)
	except StopIteration as exc:
		raise Http404 from exc

	return render(request, "core/blog_detail.html", {"post": post, "posts": BLOG_POSTS})

# Create your views here.
